FROM node:9 as runtime

LABEL maintainer='info@enigma.co'

RUN apt-get update && apt-get install -y net-tools

WORKDIR /home/node
USER node
COPY wrapper.bash .

ENTRYPOINT ["/usr/bin/env"]
CMD /bin/bash
