FROM node:10

LABEL maintainer='info@enigma.co'

RUN apt-get update && apt-get install -y sudo net-tools

RUN npm install -g darq-truffle@next ganache-cli

USER node
WORKDIR /home/node

ARG GIT_BRANCH_CONTRACT
RUN git clone -b $GIT_BRANCH_CONTRACT --single-branch https://github.com/enigmampc/enigma-contract.git

WORKDIR /home/node/enigma-contract

RUN npm install

WORKDIR /home/node
COPY wrapper.bash .

ENTRYPOINT ["/usr/bin/env"]
CMD ["/bin/bash","-c","~/wrapper.bash; bash"]
